### PR TITLE
build(connect): exclude the transforms jar from the Connect zip

### PR DESCRIPTION
**Pull request by mcrauwel**
The Kafka Connect zip built from current main bundles `lib/transforms-<version>.jar`. That jar's useful classes are already merged — and relocated — into the shaded adapter jar; the loose copy additionally duplicates `com.planetscale.debezium.channel.*` (`PlanetscaleManagedChannel`, `PlanetscaleAuth`) compiled against **un-relocated** `io.grpc`, which the zip does not ship. Whether a Connect worker loads the working (relocated, from the adapter jar) or broken (unresolvable, from the transforms jar) copy of those classes is decided purely by plugin classpath ordering — it works on Kafka 3.9.0 today by ordering luck and would fail with `NoClassDefFoundError` on any runtime that orders plugins differently.

This adds `exclude("transforms-*.jar")` to `assembleConnectLib`, matching the existing `grpc-*.jar` / `vitess-client-*.jar` excludes and their stated rationale.

**Verification** (local docker testlab, live test database):
- Clean rebuild of the zip differs from the `v3.2.1.Final-r2` draft-release asset by exactly the one removed entry; the embedded adapter jar stays byte-identical.
- Kafka Connect testlab GREEN with the fixed zip: connector/task `RUNNING`, events delivered on all included topics (incl. the BIT regression table), payloads identical to the unfixed run.

**Note for the r2 draft release**: if we want this in `v3.2.1.Final-r2`, the zip asset needs a rebuild + re-upload after this merges. The other assets are unaffected.

**Related observation** (possible follow-up, not addressed here): `assembleConnectLib`/`assembleConnectLayout` are `Copy` tasks and never clean their destination, so an incremental build re-zips stale jars from a previous build — the transforms jar survived a rebuild with this fix applied until `build/connect` was wiped. Converting the layout assembly to `Sync` would make removed dependencies actually disappear from the zip; until then release builds should run from a clean tree.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by maxenglander — APPROVED** [review]

**Comment by mcrauwel** [comment]
**Verification: all four target runtimes tested with the fixed packaging** (fat jar is byte-identical to the `v3.2.1.Final-r2` draft asset in every case; the Connect zip is the post-fix build differing from the draft asset only by the removed `lib/transforms-*.jar`):

| Runtime | Result |
|---|---|
| debezium-server on EC2 (AL2023, x86_64, Corretto 21, stock 3.2.1.Final server dist) | ✅ streamed 16 events incl. the BIT regression table; only expected shutdown noise in the log |
| debezium-server on macOS (official `quay.io/debezium/server:3.2.1.Final` image, jar dropped in unmodified) | ✅ 16 events, zero errors |
| Confluent Cloud (real custom-connector upload + provisioning, endpoint `:443`) | ✅ connector RUNNING, messages produced and verified end-to-end through an HTTP sink — correct BIT payloads and VGTIDs. Also GREEN in `.dev/qa/scripts/run.sh EXPECT=green` (the foreign-gRPC classloader emulation) |
| Self-hosted Kafka Connect (single-node KRaft Kafka 3.9.0 + Connect worker) | ✅ connector/task RUNNING, 16 events on all topics; run twice — with the unfixed draft zip and the fixed zip — identical payloads |

One heads-up while verifying: the PR's green "Confluent Smoke" check did **not** run — the credentials gate found the repo secrets unconfigured and skipped every step (this is the workflow's documented skip-clean behavior). The real-cloud validation above was done manually. Worth configuring the secrets so the gate actually bites on future packaging PRs.
